## Importing PyTorch

In [1]:
import torch
torch.__version__

'2.5.1'

## Creating Tensors
# Lets create Scalar

In [2]:
# Scalar
x = torch.tensor(42)
x

tensor(42)

In [7]:
# Dimension of scalar
x.ndim

0

In [8]:
# scalar item
x.item()

42

## Vector

In [9]:
# Vector
v = torch.tensor([2,6, 7])
v

tensor([2, 6, 7])

In [10]:
# Vector dimension
v.ndim

1

In [12]:
# Vector Shape
v.shape

torch.Size([3])

In [15]:
# Vector Matrix
m = torch.tensor([[6,8,7],
                  [7,3,0]])
m

tensor([[6, 8, 7],
        [7, 3, 0]])

In [16]:
# matrix dimension
m.ndim

2

In [17]:
# matrix shape
m.shape

torch.Size([2, 3])

## Tensors

In [26]:
# Create tensor
t = torch.tensor([[[1,7,9],
                  [6,8,9],
                  [6,7,4]]])
t

tensor([[[1, 7, 9],
         [6, 8, 9],
         [6, 7, 4]]])

In [27]:
# tensor dimension
t.ndim

3

In [28]:
# tensor shape
t.shape

torch.Size([1, 3, 3])

## Random Tensors

In [39]:
# Create Random Tensor of size (3,4)
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.3867, 0.5445, 0.7923, 0.4727],
         [0.8240, 0.3155, 0.3577, 0.0454],
         [0.7461, 0.7560, 0.8074, 0.9094]]),
 torch.float32)

In [41]:
# Create random Tensor of size (224, 224, 3)
large_tensor = torch.rand(size= (224, 224,3))
large_tensor.size(), large_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and Ones

In [44]:
# Create all Zeros Tenors
zero_tensors = torch.zeros(size=(3,4))
zero_tensors, zero_tensors.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [45]:
# Create a tensor of all ones
ones_tensors = torch.ones(size=(3, 5))
ones_tensors, ones_tensors.dtype

(tensor([[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]),
 torch.float32)